---


- name: Install MySQL
  apt: 
    name: "{{ item }}"
    update_cache: yes 
    state: present
  sudo: yes
  with_items:
    - python-mysqldb
    - mysql-server

- name: Start the MySQL service
  sudo: yes
  service: 
    name: mysql 
    state: started
    enabled: true
- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: 
    name: "{{ db_user }}" 
    host: "{{ item }}" 
    password: "{{ db_password }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - 10.0.0.11
    - 10.0.0.12
    - 10.0.0.13
    - ::1
    - localhost 



- name: Create a new database with name 'webapp'
  mysql_db:
    name: webapp
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
  register: db_created

- name: Copy SQL config file
  sudo: yes
  copy: >
    src=my.cnf
    dest="/etc/mysql/my.cnf"
    mode=755
  notify: restart mysql



- name: Copy SQL Dump
  sudo: yes
  copy: >
    src=pets.sql
    dest="/tmp/pets.sql"
    mode=755

- name: Import database
  sudo: yes
  mysql_db:
    state: import
    name: webapp
    target: "/tmp/pets.sql"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
  when: db_created.changed

- name: Create prometheus service accounts
  sudo: yes
  user: 
    name: prometheus
    shell: /bin/false
    create_home: no   

- name: Create node_exporter account
  sudo: yes
  user:
    name: node_exporter
    shell: /bin/false
    create_home: no

- name: Create /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Create /var/lib/prometheus
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Download Prometheus
  sudo: yes
  unarchive:
    src:  https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move prometheus to /usr/local/bin/
  sudo: yes
  command: cp /tmp/prometheus-2.0.0.linux-amd64/prometheus /usr/local/bin/ 

- name: Move promtool to /usr/local/bin/
  sudo: yes
  command: cp /tmp/prometheus-2.0.0.linux-amd64/promtool /usr/local/bin/

- name: Set ownership prometheus
  sudo: yes
  file: 
    path: /usr/local/bin/prometheus
    owner: prometheus
    group: prometheus

- name: Set ownership promtool
  sudo: yes
  file: 
    path: /usr/local/bin/promtool
    owner: prometheus
    group: prometheus
   
#sudo cp -r prometheus-2.0.0.linux-amd64/consoles /etc/prometheus
#sudo cp -r prometheus-2.0.0.linux-amd64/console_libraries /etc/prometheus
#sudo chown -R prometheus:prometheus /etc/prometheus/consoles
#sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries
#rm -rf prometheus-2.0.0.linux-amd64.tar.gz prometheus-2.0.0.linux-amd64
